name: Run Java Program

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run the Java program'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compile Java Program
        run: javac Main.java

      - name: Run Java Program
        run: java Main
